- hosts: all
  sudo: yes
  roles:
  - { role: malk.java8-oracle }
  - { role: thydel.vagrant, vagrant_baseurl: "https://dl.bintray.com/mitchellh/vagrant", vagrant_debfile: vagrant_1.7.4_x86_64.deb, vagrant_debdir: /tmp }
  - { role: migibert.terraform, terraform_version: 0.6.6 }
  tasks:
  - name: install debian packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      force: yes
    with_items:
    - vim
    - git
    - subversion
    - python-dev
    - python-pip
    - ruby-dev
    - rubygems
    - maven
    - mongodb-clients
    - mysql-client

  - name: install pip packages
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
    - virtualenv

  - name: install gem packages
    gem:
      name: "{{ item }}"
      state: latest
    with_items:
    - rake
    - bundler
    - cucumber
    - rubocop

  - name: download tools 
    get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
    with_items:
    - { url: 'https://github.com/atom/atom/releases/download/v1.0.19/atom-amd64.deb', dest: /tmp/atom-1.0.19.deb }
    - { url: 'https://download.jetbrains.com/idea/ideaIU-15.0.1.tar.gz', dest: /tmp/idea-15.0.1.tar.gz }
    - { url: 'http://robomongo.org/files/linux/robomongo-0.8.5-x86_64.deb', dest: /tmp/robomongo-0.8.5.deb }

  - name: install deb tools
    apt: 
      deb: "{{ item }}"
    with_items:
    - /tmp/atom-1.0.19.deb
    - /tmp/robomongo-0.8.5.deb

  - name: create intellij directory
    file:
      path: /opt/intellij
      state: directory

  - name: install intellij
    unarchive:
      copy: no
      src: /tmp/idea-15.0.1.tar.gz
      dest: /opt/intellij
