- hosts: all
  sudo: yes
  tasks:
  - name: install debian packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      force: yes
    with_items:
    - automake
    - autoconf
    - libssl-dev
    - vim
    - git
    - subversion
    - python-dev
    - python-pip
    - python3-dev
    - ruby-dev
    - rubygems
    - rbenv
    - maven
    - mongodb-clients
    - mysql-client
    - terminator
    - pidgin
    - konversation

  - name: install pip packages
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
    - virtualenv
    - yoda

  - name: install gem packages
    gem:
      name: "{{ item }}"
      state: latest
    with_items:
    - rake
    - bundler
    - cucumber
    - rubocop

  - name: download ides
    get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
    with_items:
    - { url: 'https://github.com/atom/atom/releases/download/v1.0.19/atom-amd64.deb', dest: "/home/{{ dev_user }}/Documents/tools/atom-1.0.19.deb" }
    - { url: 'https://download.robomongo.org/0.8.5/linux/robomongo-0.8.5-x86_64.deb', dest: "/home/{{ dev_user }}/Documents/tools/robomongo-0.8.5.deb" }
    - { url: 'https://download.jetbrains.com/idea/ideaIC-15.0.1.tar.gz', dest: "/home/{{ dev_user }}/Documents/tools/idea-15.0.1.tar.gz" }
    - { url: 'https://download.jetbrains.com/python/pycharm-community-5.0.1.tar.gz', dest: "/home/{{ dev_user }}/Documents/tools/pycharm-5.0.1.tar.gz" }
    tags: ide

  - name: install deb ide
    apt: 
      deb: "{{ item }}"
    with_items:
    - /home/{{ dev_user }}/Documents/tools/atom-1.0.19.deb
    - /home/{{ dev_user }}/Documents/tools/robomongo-0.8.5.deb
    tags: ide

  - name: create ide directory
    file:
      path: "/opt/{{ item }}"
      state: directory
    with_items:
    - intellij
    - pycharm
    tags: ide

  - name: install ide
    unarchive:
      copy: no
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - { src: "/home/{{ dev_user }}/Documents/tools/idea-15.0.1.tar.gz", dest: /opt/intellij }
    - { src: "/home/{{ dev_user }}/Documents/tools/pycharm-5.0.1.tar.gz", dest: /opt/pycharm }
    tags: ide

  - name: create development directory
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ dev_user }}"
      group: "{{ dev_user }}"
      recurse: yes
    with_items:
    - /home/{{dev_user}}/Documents/projects
    - /home/{{dev_user}}/Documents/projects/go
    - /home/{{dev_user}}/Documents/projects/github

- hosts: all
  sudo: yes
  roles:
  - { role: malk.java8-oracle }
  - { role: thydel.vagrant, vagrant_baseurl: "https://releases.hashicorp.com/vagrant/1.8.1", vagrant_debfile: vagrant_1.8.1_x86_64.deb, vagrant_debdir: "/home/{{ dev_user }}/Documents/tools" }
  - { role: migibert.terraform, terraform_version: 0.6.7 }
  - { role: angstwad.docker_ubuntu }
  - { role: playlist.go, go_version: 1.5.1, go_path: "/home/{{dev_user}}/Documents/projects/go", go_tarball_checksum: 2593132ca490b9ee17509d65ee2cd078441ff544899f6afb97a03d08c25524e7 }
  tasks:
  - name: let dev_user be go path owner
    file:
      path: "/home/{{ dev_user }}/Documents/projects/go"
      owner: "{{ dev_user }}"
      group: "{{ dev_user }}"
      recurse: yes
