- hosts: all
  become: yes
  tasks:

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ dev_user }}"
      group: "{{ dev_user }}"
      recurse: yes
    with_items:
    - /home/{{dev_user}}/Documents/tools
    - /home/{{dev_user}}/Documents/projects
    - /home/{{dev_user}}/Documents/projects/go
    - /home/{{dev_user}}/Documents/projects/github

  - name: install debian packages
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      force: yes
    with_items:
    - automake
    - autoconf
    - libssl-dev
    - vim
    - git
    - subversion
    - openjdk-9-jdk
    - python-dev
    - python-pip
    - python3-dev
    - ruby-dev
    - rubygems
    - rbenv
    - maven
    - mongodb-clients
    - mysql-client
    - terminator
    - pidgin
    - konversation

  - name: install pip packages
    pip:
      name: "{{ item }}"
      state: latest
      executable: "/home/{{ dev_user }}/.local/bin/pip"
    with_items:
    - virtualenv
    - yoda

  - name: install gem packages
    gem:
      name: "{{ item }}"
      state: latest
    with_items:
    - rake
    - bundler
    - cucumber
    - rubocop

  - name: download ides
    get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
    with_items:
    - { url: 'https://github.com/atom/atom/releases/download/v1.13.1/atom-amd64.deb', dest: "/home/{{ dev_user }}/Documents/tools/atom-1.13.1.deb" }
    - { url: 'https://download.robomongo.org/0.9.0/linux/robomongo-0.9.0-linux-x86_64-0786489.tar.gz', dest: "/home/{{ dev_user }}/Documents/tools/robomongo-0.9.0.tar.gz" }
    - { url: 'https://download.jetbrains.com/idea/ideaIC-2016.3.4.tar.gz', dest: "/home/{{ dev_user }}/Documents/tools/ideaIC-2016.3.4.tar.gz" }
    - { url: 'https://download.jetbrains.com/python/pycharm-community-2016.3.2.tar.gz', dest: "/home/{{ dev_user }}/Documents/tools/pycharm-community-2016.3.2.tar.gz" }
    tags: ide

  - name: install deb ide
    apt: 
      deb: "{{ item }}"
    with_items:
    - /home/{{ dev_user }}/Documents/tools/atom-1.13.1.deb
    tags: ide

  - name: create ide directory
    file:
      path: "/opt/{{ item }}"
      state: directory
    with_items:
    - intellij
    - pycharm
    - robomongo
    tags: ide

  - name: install ide
    unarchive:
      copy: no
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - { src: "/home/{{ dev_user }}/Documents/tools/ideaIC-2016.3.4.tar.gz", dest: /opt/intellij }
    - { src: "/home/{{ dev_user }}/Documents/tools/pycharm-community-2016.3.2.tar.gz", dest: /opt/pycharm }
    - { src: "/home/{{ dev_user }}/Documents/tools/robomongo-0.9.0.tar.gz", dest: /opt/robomongo }
    tags: ide

- hosts: all
  sudo: yes
  roles:
  - { role: thydel.vagrant, vagrant_baseurl: "https://releases.hashicorp.com/vagrant/1.9.1", vagrant_debfile: "vagrant_1.9.1_x86_64.deb", vagrant_debdir: "/home/{{ dev_user }}/Documents/tools" }
  - { role: migibert.terraform, terraform_version: 0.8.5 }
  - { role: angstwad.docker_ubuntu }
  - { role: jacobwgillespie-ansible.go, go_version: 1.7.5, go_path: "/home/{{dev_user}}/Documents/projects/go", go_tarball_checksum: 2e4dd6c44f0693bef4e7b46cc701513d74c3cc44f2419bf519d7868b12931ac3 }
  tasks:
  - name: let dev_user be go path owner
    file:
      path: "/home/{{ dev_user }}/Documents/projects/go"
      owner: "{{ dev_user }}"
      group: "{{ dev_user }}"
      recurse: yes
